name: Register Actions App

on:
  workflow_dispatch:

jobs:
  poke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dummy write to trigger permission registration
        run: echo "GitHub Actions app poke" >> dummy.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dummy.txt
          git commit -m "Trigger app registration"
          git push origin HEAD:register-actions-temp
